language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests/FactureTest.py
  - python -m unittest tests/mock_demo.py
  - python -m pytest tests/pytest_mock_demo.py

